excerpt_separator: ""
pygments: true
markdown: Brasil
url: https://wesley09.github.io
title: Wesley09 Android Developer´s
tagline: "Making life hard for others since 2003"
description: I will post Android-related stuff here &#128522;
paginate: 5