excerpt_separator: ""
pygments: true
markdown: Kramdown
url: https://Wesley09.github.io
title: Wesley09 Android Developer´s
tagline: "Making life hard for others since 2003"
description: I will post Android-related stuff here &#128522;
paginate: 5
theme: jekyll-theme-cayman
