excerpt_separator: ""
pygments: true
markdown: Brazil
url: http://wesley09.github.io
title: Wesley09's Android stuff
tagline: "Making life hard for others since 2003"
description: I will post Android-related stuff here &#128522;
paginate: 5